export const ERROR_CODES = {
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // Workflow
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  APPROVAL_BLOCKED_UNRESOLVED_COMMENTS: 'APPROVAL_BLOCKED_UNRESOLVED_COMMENTS',
  APPROVAL_BLOCKED_CRITICAL_AI_FINDINGS: 'APPROVAL_BLOCKED_CRITICAL_AI_FINDINGS',
  MISSING_REQUIRED_COMMENT: 'MISSING_REQUIRED_COMMENT',
  REQUEST_NOT_IN_VALID_STATE: 'REQUEST_NOT_IN_VALID_STATE',

  // IA
  AI_NOT_AVAILABLE: 'AI_NOT_AVAILABLE',
  AI_RATE_LIMIT_EXCEEDED: 'AI_RATE_LIMIT_EXCEEDED',
  AI_PARSE_ERROR: 'AI_PARSE_ERROR',
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',

  // Assets
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_ALLOWED: 'FILE_TYPE_NOT_ALLOWED',
  UPLOAD_FAILED: 'UPLOAD_FAILED',

  // General
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  CONFLICT: 'CONFLICT',
  INVALID_STATE: 'INVALID_STATE',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
